apiVersion: secrets-store.csi.x-k8s.io/v1  # Specifies the version of the CSI Secret Store API
kind: SecretProviderClass  # Defines this as a SecretProviderClass object
metadata:
  name: rentzone-secret  # The name of the SecretProviderClass
  namespace: rentzone  # The Kubernetes namespace in which this is defined
spec:
  provider: aws  # Specifies the provider for secrets, in this case, AWS
  parameters:
    objects: |
        - objectName: <arn-of-the-secret-you-created-in-secret-manager>  # ARN of the AWS Secret Manager secret
          objectAlias: "app-secret"  # Alias for the object, used as reference in the application
